### ISSUE TITLE
训练的配置文件能给看一下吗？

### ISSUE THREAD

**Issue by HaiLongEmb** [LKKlein/AI-Insects-Challenge#1]
你好，感谢你的分享，在迁移训练yolov3_resnet50vd_dcn这个模型的时候，yolov3_r50vd_dcn.yml配置文件都怎么设置的可否给看一下。

**Comment by LKKlein** [comment]
@HaiLongEmb 
你指的配置文件是PaddleDetection的配置文件吗？那个配置文件我迭代了好几十个，可以给你一份最初的配置，里面有些路径是我个人电脑的路径，使用的时候记得修改。另外，对于数据集，可能你需要先把它整理成VOC数据集的格式才能使用，具体格式可以下载一份VOC的测试看一下。

另外，学习率那里的余弦衰减也是我自己在PaddleDetection下实现的，你可以参照他的样例也实现一下，或者改成默认的也行，另外后续训练的时候，我在YoloV3和YoloHead的类里加入了一些参数，用来冻结层。那些参数直接在这里的配置下添加就行，方法都是一样的。
```yaml
architecture: YOLOv3
train_feed: YoloTrainFeed
eval_feed: YoloEvalFeed
test_feed: YoloTestFeed
use_gpu: true
max_iters: 100000
log_smooth_window: 100
log_iter: 100
save_dir: /world/data-c40/lvkun/self/projects/insects/v2-r50-vd/pretrain
snapshot_iter: 500
metric: VOC
map_type: 11point
pretrain_weights: https://paddlemodels.bj.bcebos.com/object_detection/yolov3_r50vd_dcn.tar
weights: /world/data-c40/lvkun/self/projects/insects/v2-r50-vd/pretrain/model_final
num_classes: 7
finetune_exclude_pretrained_params: ['yolo_output']

YOLOv3:
  backbone: ResNet
  yolo_head: YOLOv3Head

ResNet:
  norm_type: sync_bn
  freeze_at: 2
  freeze_norm: false
  norm_decay: 0.
  depth: 50
  feature_maps: [3, 4, 5]
  variant: d
  dcn_v2_stages: [5]

YOLOv3Head:
  anchor_masks: [[6, 7, 8], [3, 4, 5], [0, 1, 2]]
  anchors: [[19, 29], [28, 20], [25, 40],
            [31, 47], [36, 37], [41, 26],
            [47, 66], [48, 33], [67, 53]]
  ignore_thresh: 0.7
  label_smooth: false
  nms:
    background_label: -1
    keep_top_k: 100
    nms_threshold: 0.45
    nms_top_k: 1000
    normalized: false
    score_threshold: 0.01

LearningRate:
  base_lr: 0.0005
  schedulers:
  - !CosineDecay
    step_each_epoch: 170
    epochs: 500
  - !LinearWarmup
    start_factor: 0.
    steps: 10000

OptimizerBuilder:
  optimizer:
    momentum: 0.9
    type: Momentum
  regularizer:
    factor: 0.0005
    type: L2

YoloTrainFeed:
  batch_size: 8
  dataset:
    dataset_dir: /world/data-c9/lvkun/self/data/insect_voc
    annotation: ImageSets/train.txt
    use_default_label: false
  sample_transforms:
    - !DecodeImage
      to_rgb: True
      with_mixup: True
    - !MixupImage
      alpha: 1.5
      beta: 1.5
    - !NormalizeBox {}
    - !RandomDistort {}
    - !ExpandImage
      max_ratio: 4
      prob: 0.5
      mean: [231.448, 236.276, 235.433]
    - !CropImage
      batch_sampler: [[1, 1, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0],
                      [1, 50, 0.3, 1.0, 0.5, 2.0, 0.1, 1.0],
                      [1, 50, 0.3, 1.0, 0.5, 2.0, 0.3, 1.0],
                      [1, 50, 0.3, 1.0, 0.5, 2.0, 0.5, 1.0],
                      [1, 50, 0.3, 1.0, 0.5, 2.0, 0.7, 1.0],
                      [1, 50, 0.3, 1.0, 0.5, 2.0, 0.9, 1.0],
                      [1, 50, 0.3, 1.0, 0.5, 2.0, 0.0, 1.0]]
    - !RandomInterpImage
      target_size: 608
    - !RandomFlipImage
      is_normalized: True
    - !NormalizeImage
      mean: [0.9076, 0.9265, 0.9232]
      std: [0.1023, 0.1095, 0.1122]
      is_scale: True
      is_channel_first: False      
    - !Permute
      to_bgr: False
  batch_transforms:
  - !RandomShape
    sizes: [320, 352, 384, 416, 448, 480, 512, 544, 576, 608, 640]
  num_workers: 10
  bufsize: 128
  with_background: false
  samples: -1
  shuffle: true
  num_max_boxes: 50
  use_process: true
  mixup_epoch: 170

YoloEvalFeed:
  batch_size: 8
  image_shape: [3, 608, 608]
  dataset:
    dataset_dir: /world/data-c9/lvkun/self/data/insect_voc
    annotation: ImageSets/val.txt
    use_default_label: false
  batch_transforms: []
  sample_transforms:
  - !DecodeImage
    to_rgb: true
    with_mixup: false
  - !ResizeImage
    interp: 2 # 2 for cv2.INTER_CUBIC
    max_size: 0
    target_size: 608
    use_cv2: true
  - !NormalizeImage
    is_channel_first: false
    is_scale: true
    mean: [0.9076, 0.9265, 0.9232]
    std: [0.1023, 0.1095, 0.1122]
  - !Permute
    channel_first: true
    to_bgr: false
  num_max_boxes: 50
  samples: -1
  shuffle: false
  with_background: false

YoloTestFeed:
  batch_size: 8
  image_shape: [3, 608, 608]
  dataset:
    dataset_dir: /world/data-c9/lvkun/self/data/insect_voc
    annotation: ImageSets/test.txt
    use_default_label: false
  batch_transforms: []
  sample_transforms:
  - !DecodeImage
    to_rgb: true
    with_mixup: false
  - !ResizeImage
    interp: 2 # 2 for cv2.INTER_CUBIC
    max_size: 0
    target_size: 608
    use_cv2: true
  - !NormalizeImage
    is_channel_first: false
    is_scale: true
    mean: [0.9076, 0.9265, 0.9232]
    std: [0.1023, 0.1095, 0.1122]
  - !Permute
    channel_first: true
    to_bgr: false
  num_max_boxes: 50
  samples: -1
  shuffle: false
  with_background: false
```

另外， 如果是我这份代码的配置文件的话，在`train`文件里的`args`参数下都有，基本都是默认参数，你也可以参考。
